-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id integer NOT NULL,
    username "char"[],
    password "char"[],
    names "char"[],
    surnames "char"[],
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id integer NOT NULL,
    role_name "char"[],
    PRIMARY KEY (role_id)
);


CREATE TABLE IF NOT EXISTS public.period
(
    period_id integer NOT NULL,
    period_name "char"[],
    PRIMARY KEY (period_id)
);

CREATE TABLE IF NOT EXISTS public.course
(
    course_id integer NOT NULL,
    course_name "char"[],
    duration_hours integer,
    PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_user_id integer NOT NULL,
    role_role_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.association
(
    association_id integer NOT NULL,
    user_id integer,
    role_id integer,
    course_id integer,
    period_id integer,
    PRIMARY KEY (association_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id integer NOT NULL,
    approved smallint,
    note double precision,
    association_id INT UNIQUE REFERENCES association(association_id),
    PRIMARY KEY (grade_id)
);

ALTER TABLE IF EXISTS public."user"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.association (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role
    ADD FOREIGN KEY (role_id)
    REFERENCES public.association (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.period
    ADD FOREIGN KEY (period_id)
    REFERENCES public.association (period_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD FOREIGN KEY (course_id)
    REFERENCES public.association (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD FOREIGN KEY (user_user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_role
    ADD FOREIGN KEY (role_role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	

END;